export const UPDATE_TASKS = 'UPDATE_TASKS';
export const TOGGLE_SERVICE_MODE = 'TOGGLE_SERVICE_MODE';
export const CHANGE_SERVICE_MODE_JOB_NAME = 'CHANGE_SERVICE_MODE_JOB_NAME';
export const TOGGLE_DELETE_TASK_MODE = 'TOGGLE_DELETE_TASK_MODE';
export const CHANGE_CURRENT_SORTING_TASK_STATUS = 'CHANGE_CURRENT_SORTING_TASK_STATUS';
export const CHANGE_CURRENT_LOCALISATION = 'CHANGE_CURRENT_LOCALISATION';
export const TOGGLE_CHOOSE_MANY_TASKS_MODE = 'TOGGLE_CHOOSE_MANY_TASKS_MODE';
export const UPDATE_CHOOSEN_TASKS_ARRAY = 'UPDATE_CHOOSEN_TASKS_ARRAY';
export const UPDATE_CHOOSED_TASKS_FROM_MANAGER_MODE = 'UPDATE_CHOOSED_TASKS_FROM_MANAGER_MODE';
export const UPDATE_FINISH_GOODS = 'UPDATE_FINISH_GOODS';
export const TOGGLE_CHOOSE_MANY_FINISHGOOD_MODE = 'TOGGLE_CHOOSE_MANY_FINISHGOOD_MODE';
export const UPDATE_CHOOSED_FINISHGOODS_FROM_MANAGER_MODE = 'UPDATE_CHOOSED_FINISHGOODS_FROM_MANAGER_MODE';
export const CHANGE_CURRENT_SORTING_FINISHGOOD_STATUS = 'CHANGE_CURRENT_SORTING_FINISHGOOD_STATUS';
export const CHANGE_CURRENT_SORTING_LOGS_STATUS = 'CHANGE_CURRENT_SORTING_LOGS_STATUS';

const actionTypes = {
    UPDATE_TASKS,
    TOGGLE_SERVICE_MODE,
    CHANGE_SERVICE_MODE_JOB_NAME,
    TOGGLE_DELETE_TASK_MODE,
    CHANGE_CURRENT_SORTING_TASK_STATUS,
    CHANGE_CURRENT_LOCALISATION,
    TOGGLE_CHOOSE_MANY_TASKS_MODE,
    UPDATE_CHOOSEN_TASKS_ARRAY,
    UPDATE_CHOOSED_TASKS_FROM_MANAGER_MODE,
    UPDATE_FINISH_GOODS,
    TOGGLE_CHOOSE_MANY_FINISHGOOD_MODE,
    UPDATE_CHOOSED_FINISHGOODS_FROM_MANAGER_MODE,
    CHANGE_CURRENT_SORTING_FINISHGOOD_STATUS,
    CHANGE_CURRENT_SORTING_LOGS_STATUS
};

export default actionTypes;
